import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../components/providers";
import { auth } from "../auth";
import { Toaster } from "@turborepo/ui";
import { OtelProvider } from "../components/otel-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans antialiased`} suppressHydrationWarning>
        <Providers
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          session={session}
        >
          <OtelProvider />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
